local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"https://github.com/folke/lazy.nvim.git",
		"--branch=stable",
		lazypath,
	})
end

vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
	spec = {
		{
			"LazyVim/LazyVim",
			import = "lazyvim.plugins",
			opts = {
				colorscheme = "catppuccin",
			},
		},
		-- { import = "skogix.plugins" },
		{ import = "skogix.plugins.disabled" },
		{ import = "skogix.plugins.ui" },
		{ import = "skogix.plugins.bufferline" },
		{ import = "skogix.plugins.cmp" },
		{ import = "skogix.plugins.harpoon" },
		{ import = "skogix.plugins.lazydev" },
		{ import = "skogix.plugins.lsp" },
		{ import = "skogix.plugins.neotree" },
		{ import = "skogix.plugins.oil" },
		{ import = "skogix.plugins.telescope" },
		{ import = "skogix.plugins.treesitter" },
		{ import = "skogix.plugins.which-key" },

		-- done
		{ import = "skogix.dev.ui.alpha" },
		{ import = "skogix.dev.editor.telescope.all-recent" },
		{ import = "skogix.dev.editor.telescope.file-browser" },
		{ import = "skogix.dev.editor.telescope.lazy" },
		{ import = "skogix.dev.editor.telescope.live-grep" },
		{ import = "skogix.dev.editor.telescope.zoxide" },
		{ import = "skogix.dev.editor.oil" },
		{ import = "skogix.dev.editor.telescope.undotree" },
		{ import = "skogix.dev.editor.docs.devdocs" },
		{ import = "skogix.todo.toggleterm" },
		{ import = "skogix.todo.copilot" },
		{ import = "skogix.todo.copilot-chat" },
		{ import = "skogix.dev.coding.cmp.dotenv" },

		-- todo
		-- { import = "skogix.dev.editor.fold" }, -- kolla promises
		-- { import = "skogix.dev.editor.telescope.luasnip" }, -- får inte att funka
		-- { import = "skogix.dev.ui.transparent" }, -- glhf wayland
		{ import = "skogix.dev.editor.search-replace" },
		{ import = "skogix.dev.editor.tabscope" },
		-- { import = "skogix.dev.coding.ai.copilot" },
		-- { import = "skogix.dev.editor.terminal.toggleterm" },
		-- { import = "skogix.dev.editor.markmap" },
		-- { import = "lazyvim.plugins.extras.editor.telescope" },
		-- { import = "skogix.dev.editor.telescope"},
		-- { import = "skogix.dev.editor.telescope.headings"},
		-- { import = "skogix.dev.editor.telescope.import" },
		-- { import = "skogix.dev.editor.telescope.media"},
		-- { import = "skogix.dev.editor.telescope.repo" },
		--   { import = "skogix.dev.editor.telescope.urlview"},
		--   { import = "skogix.dev.editor.telescope.workspaces"},
		-- { import = "skogix.dev.editor.treesitter-playground" },
		--   { import = "skogix.dev.editor.carbon-now"},
		--   { import = "skogix.dev.editor.ccc"},
		--   { import = "skogix.dev.editor.codesnap"},
		--   { import = "skogix.dev.editor.compiler"},
		-- { import = "skogix.dev.editor.dev-container"},
		--   { import = "skogix.dev.editor.five-server"},
		--   { import = "skogix.dev.editor.flash-extended"},
		-- { import = "skogix.dev.editor.gitsigns-extended"},
		--   { import = "skogix.dev.editor.hover"},
		--   { import = "skogix.dev.editor.leap-spooky"},
		-- { import = "skogix.dev.editor.live-server"},
		-- { import = "skogix.dev.editor.neo-tree-extended"},
		--   { import = "skogix.dev.editor.numb"},
		-- --   { import = "skogix.dev.editor.outline-extended"},
		--   { import = "skogix.dev.editor.package-info"},
		--   { import = "skogix.dev.editor.regex"},
		--   { import = "skogix.dev.editor.retirement"},
		--   { import = "skogix.dev.editor.spectre"},
		--   { import = "skogix.dev.editor.ssr"},
		--   { import = "skogix.dev.editor.suda"},
		--   { import = "skogix.dev.editor.treesitter-playground"},
		--   { import = "skogix.dev.editor.trouble-extended"},
		--   { import = "skogix.dev.editor.winshift"},
		--   { import = "skogix.dev.editor.terminal.floaterm"},
		--   { import = "skogix.dev.coding.annotation" },
		--   { import = "skogix.dev.coding.cmp-extended" },
		--   { import = "skogix.dev.coding.debugprint" },
		--   { import = "skogix.dev.coding.ibus" },
		--   { import = "skogix.dev.coding.luasnip-extended" },
		--   { import = "skogix.dev.coding.multicursor" },
		--   { import = "skogix.dev.coding.recorder" },
		--   { import = "skogix.dev.coding.refactoring" },
		--   { import = "skogix.dev.coding.snippets" },
		--   { import = "skogix.dev.coding.sniprun" },
		--   { import = "skogix.dev.coding.ultimate-autopair" },
		--   { import = "skogix.dev.coding.yanky-extended" },
		-- { import = "skogix.dev.coding.ai.avante" },
		--   { import = "skogix.dev.coding.ai.codecompanion" },
		--   { import = "skogix.dev.coding.ai.codeium" },
		-- { import = "skogix.dev.coding.ai.gen" },
		-- { import = "skogix.dev.coding.ai.gpt" },
		--   { import = "skogix.dev.coding.ai.neocodeium" },
		--   { import = "skogix.dev.coding.cmp.autopairs" },
		--   { import = "skogix.dev.coding.cmp.emoji" },
		--   { import = "skogix.dev.coding.cmp.fonts" },
		--   { import = "skogix.dev.coding.cmp.nerd-fonts" },
		--   { import = "skogix.dev.coding.cmp.npm" },
		--   { import = "skogix.dev.coding.cmp.rg" },
		--   { import = "skogix.dev.coding.cmp.under-comparator" },
		--   { import = "skogix.dev.coding.cmp.yanky" },
		--   { import = "skogix.dev.coding.treesitter.auto-indent" },
		--   { import = "skogix.dev.coding.treesitter.endwise" },
		--   { import = "skogix.dev.coding.treesitter.guess-indent" },
		--   { import = "skogix.dev.coding.treesitter.mini-align" },
		--   { import = "skogix.dev.coding.treesitter.node-action" },
		--   { import = "skogix.dev.coding.treesitter.puppeteer" },
		--   { import = "skogix.dev.coding.treesitter.sibling-swap" },
		--   { import = "skogix.dev.coding.treesitter.spider" },
		--   { import = "skogix.dev.coding.treesitter.text-case" },
		--   { import = "skogix.dev.coding.treesitter.various-textobjs" },
		--   { import = "skogix.dev.coding.treesitter.wildfire" },
		--   { import = "skogix.dev.ui.block" },
		--   { import = "skogix.dev.ui.breadcrumbs" },
		-- { import = "skogix.dev.ui.bufferline-extended" },
		--   { import = "skogix.dev.ui.colorful-winsep" },
		--   { import = "skogix.dev.ui.comment-box" },
		--   { import = "skogix.dev.ui.context" },
		--   { import = "skogix.dev.ui.dashboard-extended" },
		--   { import = "skogix.dev.ui.diagflow" },
		--   { import = "skogix.dev.ui.edgy-extended" },
		--   { import = "skogix.dev.ui.fidget" },
		--   { import = "skogix.dev.ui.helpview" },
		--   { import = "skogix.dev.ui.highlight-colors" },
		--   { import = "skogix.dev.ui.highlight-undo" },
		--   { import = "skogix.dev.ui.image" },
		--   { import = "skogix.dev.ui.img-clip" },
		--   { import = "skogix.dev.ui.import-cost" },
		--   { import = "skogix.dev.ui.inline-fold" },
		--   { import = "skogix.dev.ui.log-highlight" },
		-- { import = "skogix.dev.ui.lualine-extended" },
		--   { import = "skogix.dev.ui.minimap" },
		--   { import = "skogix.dev.ui.modes" },
		--   { import = "skogix.dev.ui.modicator" },
		-- { import = "skogix.dev.ui.noice-extended" },
		--   { import = "skogix.dev.ui.nvim-notify-extended" },
		--   { import = "skogix.dev.ui.rainbow-delimeters" },
		--   { import = "skogix.dev.ui.reactive" },
		--   { import = "skogix.dev.ui.scrollbar" },
		--   { import = "skogix.dev.ui.smooth-scrolling" },
		--   { import = "skogix.dev.ui.specs" },
		--   { import = "skogix.dev.ui.status-column" },
		--   { import = "skogix.dev.ui.sunglasses" },
		--   { import = "skogix.dev.ui.theme-loader" },
		--   { import = "skogix.dev.ui.tiny-inline-diagnostic" },
		-- { import = "skogix.dev.ui.which-key-extended" },
		--   { import = "skogix.dev.ui.windows" },
		--   { import = "skogix.dev.ui.zen-mode" },

		-- { import = "lazyvim.plugins.extras.editor.fzf" },
		-- { import = "skogix.disabled" },
	},
	ui = {
		backdrop = 100,
	},
	defaults = {
		lazy = true,
		version = false, -- always use the latest git commit
		-- version = "*", -- try installing the latest stable version for plugins that support semver
		keymaps = false,
	},
	local_spec = true,
	checker = { enabled = true }, -- automatically check for plugin updates
	performance = {
		cache = {
			enabled = true,
			-- disable_events = {},
		},
		rtp = {
			-- disable some rtp plugins
			disabled_plugins = {
				"gzip",
				"tarPlugin",
				"tohtml",
				"tutor",
				"netrwPlugin",
				"zipPlugin",
			},
		},
	},
})

require("lazy").setup(specs)
