-- This file contains the plugin configurations for the skogix setup.

return {
    ["skogix.plugins.chatgpt"] = true,
    ["skogix.plugins.cmp"] = true,
    ["skogix.plugins.colorscheme"] = true,
    ["skogix.plugins.git"] = true,
    ["skogix.plugins.harpoon"] = true,
    ["skogix.plugins.lazydev"] = true,
    ["skogix.plugins.lsp"] = true,
    ["skogix.plugins.oil"] = true,
    ["skogix.plugins.telescope"] = true,
    ["skogix.plugins.treesitter"] = true,
    ["skogix.plugins.which-key"] = true,

    -- ["skogix.todo.recorder"] = false,
    ["skogix.todo.aider"] = true,
    ["skogix.todo.toggleterm"] = true,
    -- ["skogix.dev.editor.terminal.toggleterm"] = true,
    -- ["avante"] = true,
    -- ["bufferline"] = true,
    -- ["codeium"] = true,
    -- ["cokeline"] = true,
    -- ["copilot-chat"] = true,
    -- ["copilot"] = true,
    -- ["cursor"] = true,
    -- ["dressing"] = true,
    -- ["enlighten"] = true,
    -- ["fzf"] = true,
    -- ["gen"] = true,
    -- ["gp"] = true,
    -- ["hello"] = true,
    -- ["lazygit"] = true,
    -- ["neoai"] = true,
    -- ["neogen"] = true,
    -- ["neorg"] = true,
    -- ["noice"] = true,
    -- ["ogpt"] = true,
    -- ["quickfix"] = true,
    -- ["winbar"] = true,
}
